services:
  couchdb:
    build: .
    ports:
      - "5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=${SERVICE_USER_COUCHDB}
      - COUCHDB_PASSWORD=${SERVICE_PASSWORD_COUCHDB}
      - SERVICE_FQDN_COUCHDB_5984
    healthcheck:
      test: curl -f -u ${SERVICE_USER_COUCHDB}:${SERVICE_PASSWORD_COUCHDB} http://localhost:5984/_up || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
