services:
  couchdb:
    build: .
    volumes:
      - couchdb-data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=${SERVICE_USER_COUCHDB}
      - COUCHDB_PASSWORD=${SERVICE_PASSWORD_COUCHDB}
      - SERVICE_FQDN_COUCHDB_5984
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  couchdb-data:
